name: Publish Library

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  test-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          registry-url: 'https://registry.npmjs.org/'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

      - name: Run tests
        run: npm test -- --watch=false --browsers=ChromeHeadless

      - name: Build library
        run: npm run build

      - name: Check if package exists on npm
        id: check-package
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          if npm view ng-solitude@$VERSION version >/dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
          else
            echo "exists=false" >> $GITHUB_OUTPUT
          fi

      - name: Publish to npm
        if: steps.check-package.outputs.exists == 'false'
        run: npm publish dist/ng-solitude --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Skip publish (already exists)
        if: steps.check-package.outputs.exists == 'true'
        run: echo "Package version already exists on npm, skipping publish" 